#!/usr/bin/env python
from django.conf import settings
settings.configure()

from django.core.urlresolvers import get_resolver, Resolver404

resolver=get_resolver("urls")

try:
    func,args,kwargs=resolver.resolve("/not_existing")
    print func,args,kwargs
except Resolver404,e:
    print e
