#!/usr/bin/env python
from datetime import datetime
from django.db import models
import django
django.setup()


# https://docs.djangoproject.com/en/dev/ref/models/fields/#default


class Model(models.Model):
    date = models.DateTimeField(auto_now_add=True, blank=True)
    # equal to:
    date = models.CharField(default=datetime.now, blank=True)

    class Meta():
        app_label = "app"


print(Model().date)
