#!/usr/bin/env python
from django.db import models
import django
django.setup()

# https://docs.djangoproject.com/en/dev/ref/models/fields/#unique


class model(models.Model):
    title = models.CharField(max_length=30, unique=True)

    class Meta():
        app_label = "app"
