#!/usr/bin/env python
from django.utils.encoding import smart_bytes

# https://docs.djangoproject.com/en/dev/ref/utils/#module-django.utils.encoding

# smart_text(s, encoding='utf-8', strings_only=False, errors='strict')
# Returns a str object representing s. Treats bytestrings using the encoding codec

bytestring = smart_bytes("bytestrings")
print(bytestring, bytestring.__class__)
