#!/usr/bin/env python
from django.utils.encoding import *

# https://docs.djangoproject.com/en/dev/ref/utils/#module-django.utils.encoding

print(uri_to_iri('/%E2%99%A5%E2%99%A5/?utf8=%E2%9C%93'))
# /♥♥/?utf8=✓

print(uri_to_iri('%A9hello%3Fworld'))
# '%A9hello%3Fworld'

# Both iri_to_uri() and uri_to_iri() functions are idempotent
some_string = '%A9hello%3Fworld'
assert iri_to_uri(iri_to_uri(some_string)) == iri_to_uri(some_string)
# So you can safely call it multiple times on the same URI/IRI without risking double-quoting problems.
