#!/usr/bin/env python
from django.db import models
from django.forms import modelformset_factory
import django
django.setup()

# https://docs.djangoproject.com/en/dev/topics/forms/modelforms/#model-formsets


class Model(models.Model):
    title = models.CharField(max_length=30)

    class Meta():
        app_label = "app"


ModelFormSet = modelformset_factory(Model, fields=('title',))
queryset = Model.objects.none()
formset = ModelFormSet(queryset=queryset)
print(formset)
